FROM python:3.12-slim

# =========================
# ENV SETTINGS
# =========================
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# =========================
# SYSTEM DEPENDENCIES (OCR + BUILD)
# =========================
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libgl1 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# =========================
# INSTALL DEPENDENCIES
# =========================
COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# =========================
# COPY PROJECT
# =========================
COPY . .

# =========================
# EXPOSE PORT
# =========================
EXPOSE 8000

# =========================
# RUN SERVER
# =========================
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]